prometheus:
  $type: namespace

  saline_enabled:
    $type: boolean
    $name: Enable Saline scrape configuration
    $default: false
    $help: Add scrape configuration of Saline to Prometheus

  saline_https_connection:
    $type: boolean
    $name: Saline secure connection (HTTPS)
    $default: true
    $help: Use HTTPS to connect to Saline

  saline_metrics_path:
    $type: text
    $name: Path to Saline metrics
    $default: /saline/metrics
    $help: Path to Saline metrics to retrive the data from

  scrape_configs:
    $type: edit-group
    $visible: false
    $minItems: 1
    $maxItems: 1
    $prototype:
      $type: group
      $key:
        $type: text
        $default: saline
      files:
        $type: edit-group
        $minItems: 1
        $maxItems: 1
        $prototype:
          $type: text
          $default: /etc/prometheus/saline.yml
