{
 "title": "Uyuni Server (with Saline)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "server",
    "query": {
     "query": "label_values(up{job=\"$job\"} , instance)"
    }
   },
   { "name": "job", "query": "mgr-server" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$server:9100\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "System Load ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(node_load1{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load1"
    },
    {
     "expr": "(node_load5{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load5"
    },
    {
     "expr": "(node_load15{instance=~\"$server:9100\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}))",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "CPU now",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode!=\"idle\"}[5m])) / count(node_cpu_seconds_total{instance=~\"$server:9100\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (node_filesystem_size_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:.*\", mode=\"user\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:.*\", mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode=\"system\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode=\"iowait\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$server:9100\", mode!~\"user|system|iowait|guest|idle\"}[5m]) or irate(node_cpu_seconds_total{instance=~\"$server:9100\", mode!~\"user|system|iowait|guest|idle\"}[5m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "network-tx"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "network-rx"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(1 - node_filesystem_avail_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"} / node_filesystem_size_bytes, \"shortdev\", \"$1\", \"device\", \"/dev/(.*)\")   ",
     "legendFormat": "{{shortdev}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((node_memory_MemAvailable{instance=~\"$server:9100\"} / node_memory_MemTotal) or (node_memory_MemAvailable_bytes{instance=~\"$server:9100\"} / node_memory_MemTotal_bytes))",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "disk-read"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{instance=~\"$server:9100\"}[5m]))",
     "legendFormat": "disk-write"
    }
   ]
  },
  {
   "title": "mount points",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}+0"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:9100\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}"
    }
   ]
  },
  { "title": "Saline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Salt Events",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(salt_events_total{instance=~\"$server:443\"}[5m])",
     "legendFormat": "Salt events"
    },
    {
     "expr": "sum(rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/new\",fun=~\"state.*\"}[5m]))",
     "legendFormat": "States apply requests"
    },
    {
     "expr": "sum(rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/ret/*\",fun=~\"state.*\"}[5m]))",
     "legendFormat": "States applied"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/new\",fun=\"test.ping\"}[5m])",
     "legendFormat": "Test ping requests"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/ret/*\",fun=\"test.ping\"}[5m])",
     "legendFormat": "Test ping returns"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/new\",fun=\"mgractionchains.resume\"}[5m])",
     "legendFormat": "Action chains resume requests"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/ret/*\",fun=\"mgractionchains.resume\"}[5m])",
     "legendFormat": "Action chains resume returns"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/new\",fun=\"saltutil.find_job\"}[5m])",
     "legendFormat": "Find job requests"
    },
    {
     "expr": "rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/ret/*\",fun=\"saltutil.find_job\"}[5m])",
     "legendFormat": "Find job returns"
    },
    {
     "expr": "sum(rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/new\",fun=~\"grains.*\"}[5m]))",
     "legendFormat": "Grains requests"
    },
    {
     "expr": "sum(rate(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/job/*/ret/*\",fun=~\"grains.*\"}[5m]))",
     "legendFormat": "Grains returns"
    },
    {
     "expr": "rate(salt_events_tags{instance=\"$server:443\",tag=\"salt/batch/*/start\"}[5m])",
     "legendFormat": "Salt batch start"
    },
    {
     "expr": "rate(salt_events_tags{instance=\"$server:443\",tag=\"salt/batch/*/done\"}[5m])",
     "legendFormat": "Salt batch done"
    },
    {
     "expr": "rate(salt_events_tags{instance=\"$server:443\",tag=\"salt/auth\"}[5m])",
     "legendFormat": "Salt auth"
    },
    {
     "expr": "sgn(round(increase(salt_events_tags_funcs{instance=\"$server:443\",tag=\"salt/key\",fun=\"delete\"}[$__rate_interval]))) * 3",
     "legendFormat": "Salt key delete"
    },
    {
     "expr": "sgn(round(increase(salt_events_trimmed_total{instance=\"$server:443\"}[$__rate_interval]))) * 5",
     "legendFormat": "Values trimmed"
    }
   ]
  },
  {
   "title": "Minions Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"seen\"}",
     "legendFormat": "seen"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"active_1m\"}",
     "legendFormat": "active 1m"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"active_5m\"}",
     "legendFormat": "active 5m"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"active_15m\"}",
     "legendFormat": "active 15m"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"active_1h\"}",
     "legendFormat": "active 1h"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"active_ever\"}",
     "legendFormat": "active ever"
    },
    {
     "expr": "salt_minions{instance=\"$server:443\",status=\"offline\"}",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Salt Events by Tags and Functions",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "round(increase(salt_events_tags_funcs{instance=\"$server:443\",tag=~\"salt/job/\\\\*/new|salt/batch/\\\\*/start|salt/wheel/\\\\*/new\"}[$__rate_interval]))",
     "legendFormat": "tag:{{tag}} fun:{{fun}}"
    },
    {
     "expr": "round(increase(salt_events_tags_funcs{instance=\"$server:443\",tag=~\"salt/job/\\\\*/ret/\\\\*|salt/batch/\\\\*/done|salt/wheel/\\\\*/ret|salt/auth\"}[$__rate_interval]))",
     "legendFormat": "tag:{{tag}} fun:{{fun}}"
    }
   ]
  },
  {
   "title": "Salt States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "round(sum(increase(salt_state_applies_status{instance=\"$server:443\",status=~\"succeeded.*\"}[$__rate_interval])))",
     "legendFormat": "States succeeded"
    },
    {
     "expr": "round(sum(increase(salt_state_applies_status{instance=\"$server:443\",status=~\"failed.*\"}[$__rate_interval])))",
     "legendFormat": "States failed"
    },
    {
     "expr": "round(sum(increase(salt_state_applies_status{instance=\"$server:443\",status=~\".*_warnings\"}[$__rate_interval])))",
     "legendFormat": "States warnings"
    },
    {
     "expr": "round(sum(increase(salt_state_applies_status{instance=\"$server:443\",status=\"errors\"}[$__rate_interval])))",
     "legendFormat": "States errors"
    },
    {
     "expr": "round(sum(increase(salt_state_applies_status{instance=\"$server:443\",status=\"test\"}[$__rate_interval])))",
     "legendFormat": "States test"
    }
   ]
  },
  { "title": "Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "JVM - Tomcat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5556\"})",
     "legendFormat": "threads"
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5556\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "operations " }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{instance=~\"$server:9187\", datname=~\"uyuni|susemanager\"}[5m])",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(pg_locks_count{instance=~\"$server:9187\" ,datname=~\"uyuni|susemanager\"})",
     "legendFormat": "locks"
    }
   ]
  },
  {
   "title": "Taskomatic Scheduler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "taskomatic_scheduler_threads{instance=~\"$server:5556\"}",
     "legendFormat": "threads total"
    },
    {
     "expr": "taskomatic_scheduler_threads_active{instance=~\"$server:5556\"}",
     "legendFormat": "threads active"
    },
    {
     "expr": "increase(taskomatic_scheduler_completed_task_count{instance=~\"$server:9800\"}[2m])",
     "legendFormat": "tasks completed"
    }
   ]
  },
  {
   "title": "JVM - Taskomatic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5557\"})",
     "legendFormat": "threads "
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5557\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Server Actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(mgr_serveractions_failed{instance=~\"$server:9187\"}[2m])",
     "legendFormat": "failed"
    },
    {
     "expr": "increase(mgr_serveractions_completed{instance=~\"$server:9187\"}[2m])",
     "legendFormat": "completed"
    },
    {
     "expr": "mgr_serveractions_picked_up{instance=~\"$server:9187\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "mgr_serveractions_queued{instance=~\"$server:9187\"}",
     "legendFormat": "picked up"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "none", "label": "tasks" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_threads{instance=~\"$server:80\"}",
     "legendFormat": "threads total"
    },
    {
     "expr": "message_queue_thread_pool_threads_active{instance=~\"$server:80\"}",
     "legendFormat": "threads active"
    },
    {
     "expr": "increase(message_queue_thread_pool_completed_task_count{instance=~\"$server:80\"}[2m])",
     "legendFormat": "tasks completed"
    }
   ]
  }
 ]
}